icon = [[
....................
....................
....................
...J..L..N..Q..9....
....................
....J..L..N..Q..9...
...1.............1..
..7..............5U.
..X..............WU.
....................
....................
..Y..............ZS.
..7..............5S.
...3.............3..
....j..l..n..q..s...
....................
...j..l..n..q..s....
....................
....................
....................
]]

a = true
b = false


t1 = hs.timer.doWhile(load("return a"), function() print("t1 - set 'a' to false to stop") end, 2)
t2 = hs.timer.doUntil(load("return b"), function() print("t2 - set 'b' to true to stop") end, 2)

t3 = hs.timer.waitWhile(load("return a"), function(_) print("t3 - you stopped t1!") ; a = true ;  t1:start() ; _:start() end, 5)
t4 = hs.timer.waitUntil(load("return b"), function(_) print("t4 - you stopped t1!") ; b = false ; t2:start() ; _:start() end, 5)
